// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dalxznbcorkylxopango.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhbHh6bmJjb3JreWx4b3BhbmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjEyMjgsImV4cCI6MjA2NjYzNzIyOH0.pO9nC4od3vGjRvPU4eOm7dOEznS5mFW1o4cN1TLUrZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);